module.exports = {
    CategoryModel:                  require('./category'),
    SubcategoryModel:               require('./subcategory'),

    FileModel:                      require('./file'),
    ForgotPasswordModel:            require('./forgotPassword'),
    EnquiryModel:                   require('./enquiry'),
    LogsModel:                      require('./logs'),
    NotificationModel:              require('./notification'),
    OtpModel:                       require('./otp'),
    ReviewModel:                    require('./review'),
    RoleModel:                      require('./role'),
    SessionModel:                   require('./session'),
    StateModel:                     require('./state'),
    TagsModel:                      require('./tags'),
    UserModel:                      require('./user'),
    BlogModel:                      require('./blog'),

    TestimonialModel:               require('./testimonial'),
    TeamModel:                      require('./team'),
    VisionModel:                    require('./vision'),
    AboutModel:                     require('./about'),
    HomeModel:                      require('./home'),

    
    SolutionModel:                  require('./solution'),
    whyChooseModel:                 require('./whychooseModel'),
    HomeBannerModel:                require('./homebannermodel'),
    JourneyModel:                     require('./journey'),
    CareerModel:                     require('./career'),
    GalleryModel:                     require('./gallerymodel'),
    CareerBenafitModel:                require('./careerbenafitmodel'),
    CareerHeadingModel:                require('./careerheadingmodel'),
    PolicyCategoryModel:                require('./policycategorymodel'),
    PolicyModel:                       require('./policymodel'),
    ContactHeadingModel:                require('./contactheadingmodel'),
    SettingModel:                       require('./settingmodel'),
    MetaModel:                          require('./metamodel'),
    FaqCategoryModel:                   require('./faqcategorymodel'),
    FaqModel:                           require('./faqmodel'),
    GalleryHeadingModel:                require('./galleryheadingmodel'),
    PaymentModel:                       require('./paymentmodel'),
    CareerJobApplyModel:                 require('./careereJobApply'),
    StateModel:                         require('./statemodel'),
    PageModel:                          require('./pagemodel'),
    PartnerModel:                       require('./partners'),
    CityModel:                          require('./citymodel'),
    ServiceModel:                       require('./servicemodel'),
    CallbackEnquiryModel:               require('./callbackenquirymodel'),
    BlogCategoryModel:                  require('./blogcategorymodel'),
    SolutionServiceModel:               require('./solutionServiceModel'),
    ServiceOfferingModel:               require('./serviceOfferingModel'),
    SolutionOverviewModel:              require('./solutionOverviewModel'),
    IndustryModel:                      require('./industryModel'),
    IndustryOfferingModel:              require('./industryOfferingModel'),
    StoryTagModel:                      require('./storyTagModel'),
    StoryModel:                         require('./storyModel'),
    CaseStudyModel:                     require('./caseStudyModel'),
    CaseStudyTagModel:                  require('./caseStudyTagModel'),
    PresenceModel:                      require('./presenceModel'),
    ContactModel:                       require('./contactModel'),
    PartnerTagModel:                    require('./partnerTagModel'),
    WhitePaperTagModel:                 require('./whitePaperTagModel'),
    WhitePaperModel:                    require('./whitePaperModel'),
    ProductivityModel:                  require('./productivityModel'),
    WorkModel:                          require('./workModel'),
    CompatativeEnquiryModel :            require('./compatativemodel'),
    WhitepaperEnquiryModel:              require('./whitepaperEnquiryModel'),
    BusinessHeadingModel:               require('./businessHeadingModel'),
    SideStoryMenu:                      require('./sideStoryMenu'),
    FinanceModel:                       require('./financeModel'),
    FinanceOfferingModel:               require('./financeOfferingModel'),
    FinanceHeadingModel:                require('./financeHeadingModel'),
    SideMenuModel:                      require('./sideMenuModel'),
    CustomerExperienceModel:            require('./customerExperienceModel'),
    CustomerBenafitModel:               require('./customerBenafitModel'),
    AwardModel:                         require('./awardModel'),
    AccreditationdModel:                require('./accreditationdModel'),
    SolutionHomeModel:                  require('./solutionHomeModel'),
    SolutionHomeListModel:              require('./solutionHomeListModel')


}